# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LfgBeta < Formula
  desc "TUI bootstrap CLI for new dev machines (beta channel)"
  homepage "https://github.com/ptmaroct/lfg"
  version "0.4.1-beta.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ptmaroct/lfg/releases/download/v0.4.1-beta.0/lfg_0.4.1-beta.0_darwin_amd64.tar.gz"
      sha256 "fa356e1d749624ea8528965c57799af658bba0194df5ffcfba2c6f2392d05e05"

      define_method(:install) do
        bin.install "lfg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ptmaroct/lfg/releases/download/v0.4.1-beta.0/lfg_0.4.1-beta.0_darwin_arm64.tar.gz"
      sha256 "9271898e684a15b6c2f334a9bcb8fd614f5abe2b897afda2d76719c3b93980cf"

      define_method(:install) do
        bin.install "lfg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ptmaroct/lfg/releases/download/v0.4.1-beta.0/lfg_0.4.1-beta.0_linux_amd64.tar.gz"
      sha256 "8274e67dd2334ea478f7d004bf8b1ad9cf90e457c8a2d18679441524d421516b"
      define_method(:install) do
        bin.install "lfg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ptmaroct/lfg/releases/download/v0.4.1-beta.0/lfg_0.4.1-beta.0_linux_arm64.tar.gz"
      sha256 "6f0128e87e7dfe5410c6a0785fe05f5586881feddbea10f90e3620302ad54ad0"
      define_method(:install) do
        bin.install "lfg"
      end
    end
  end

  def caveats
    <<~EOS
      lfg-beta is the preview channel — expect rough edges.
      Stable lives at `brew install ptmaroct/tap/lfg`.
    EOS
  end

  test do
    system "#{bin}/lfg", "version"
  end
end
