# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LfgBeta < Formula
  desc "TUI bootstrap CLI for new dev machines (beta channel)"
  homepage "https://github.com/ptmaroct/lfg"
  version "0.4.0-beta.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ptmaroct/lfg/releases/download/v0.4.0-beta.0/lfg_0.4.0-beta.0_darwin_amd64.tar.gz"
      sha256 "3e9deca56917bd538272348f44387d541344d5887ecfe4f4c507c33c405c89f3"

      define_method(:install) do
        bin.install "lfg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ptmaroct/lfg/releases/download/v0.4.0-beta.0/lfg_0.4.0-beta.0_darwin_arm64.tar.gz"
      sha256 "04e66616ceab3ce5e6f7758d799319b65ef4c0e6687d378c93d9a51536866e4e"

      define_method(:install) do
        bin.install "lfg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ptmaroct/lfg/releases/download/v0.4.0-beta.0/lfg_0.4.0-beta.0_linux_amd64.tar.gz"
      sha256 "f74064a59d9b67c87d20299345de6b1441d409ab74ae55123dc4efe189fa1be6"
      define_method(:install) do
        bin.install "lfg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ptmaroct/lfg/releases/download/v0.4.0-beta.0/lfg_0.4.0-beta.0_linux_arm64.tar.gz"
      sha256 "ea6845b2c7b9650986854d7d8641e4909467fca2250303090868019c509b7289"
      define_method(:install) do
        bin.install "lfg"
      end
    end
  end

  def caveats
    <<~EOS
      lfg-beta is the preview channel — expect rough edges.
      Stable lives at `brew install ptmaroct/tap/lfg`.
    EOS
  end

  test do
    system "#{bin}/lfg", "version"
  end
end
