# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lfg < Formula
  desc "TUI bootstrap CLI for new dev machines"
  homepage "https://github.com/ptmaroct/lfg"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ptmaroct/lfg/releases/download/v0.4.0/lfg_0.4.0_darwin_amd64.tar.gz"
      sha256 "d2a5a9f967266478f244daf8f40bc7925c32e9d984b8f0b3081958a9cb703627"

      define_method(:install) do
        bin.install "lfg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ptmaroct/lfg/releases/download/v0.4.0/lfg_0.4.0_darwin_arm64.tar.gz"
      sha256 "8298169a40024e22a464b54c7e82e83de190d3a46060b1d0e1c04d9a0eb4e6ff"

      define_method(:install) do
        bin.install "lfg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ptmaroct/lfg/releases/download/v0.4.0/lfg_0.4.0_linux_amd64.tar.gz"
      sha256 "fba9396d70f9e1b5a8f52150e1564063268f8756502b864ddb8f2cbc57d0af0d"
      define_method(:install) do
        bin.install "lfg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ptmaroct/lfg/releases/download/v0.4.0/lfg_0.4.0_linux_arm64.tar.gz"
      sha256 "66fa2d0a1a968f64d7f3595b326ab4f62bdd676b3adcfdf25d2cfe0a2bd64645"
      define_method(:install) do
        bin.install "lfg"
      end
    end
  end

  test do
    system "#{bin}/lfg", "version"
  end
end
