# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lfg < Formula
  desc "TUI bootstrap CLI for new dev machines"
  homepage "https://github.com/ptmaroct/lfg"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ptmaroct/lfg/releases/download/v0.3.2/lfg_0.3.2_darwin_amd64.tar.gz"
      sha256 "d32fa67f35ca4281a3afac0f3b8f1b2ed7f409d86fe441b3a91cc801b3d28e28"

      define_method(:install) do
        bin.install "lfg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ptmaroct/lfg/releases/download/v0.3.2/lfg_0.3.2_darwin_arm64.tar.gz"
      sha256 "c6d8114fd022136ec54a5c1f4f60d5dad0749d1773aa7c450212d727b62576b6"

      define_method(:install) do
        bin.install "lfg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ptmaroct/lfg/releases/download/v0.3.2/lfg_0.3.2_linux_amd64.tar.gz"
      sha256 "2d097bb6c7027d54b57c8df7d553885cafd2ad26c2bed0bedc0afffd0f9aac92"
      define_method(:install) do
        bin.install "lfg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ptmaroct/lfg/releases/download/v0.3.2/lfg_0.3.2_linux_arm64.tar.gz"
      sha256 "7869b4ea9e07e8cad64a560f7ec68d209f7b4e2c48356a5fe94543c4d4a336f3"
      define_method(:install) do
        bin.install "lfg"
      end
    end
  end

  test do
    system "#{bin}/lfg", "version"
  end
end
